/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Login
         * @description Envoie le navigateur chez le fournisseur.
         */
        get: operations["login_api_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Callback
         * @description Retour du fournisseur. Redirige toujours vers l'application, pas de JSON.
         *
         *     C'est le navigateur qui arrive ici, pas le code de l'interface : une erreur
         *     doit rester lisible dans la page, d'ou le passage par un parametre plutot
         *     qu'un corps d'erreur que personne n'afficherait.
         */
        get: operations["callback_api_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Qui je suis, et comment l'application authentifie.
         *
         *     Toujours 200, jamais 401 : l'interface a besoin de savoir s'il faut
         *     proposer une connexion, ce qu'un code d'erreur ne dirait pas.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Ferme la session locale, et indique ou poursuivre chez le fournisseur.
         *
         *     La deconnexion globale reste au choix de l'interface : sur un poste
         *     partage on la veut, sur un poste personnel elle obligerait a ressaisir
         *     son mot de passe partout.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List People
         * @description Les personnes connues, pour choisir avec qui partager une playlist.
         *
         *     Accessible a tout le monde et non aux seuls administrateurs : sans elle,
         *     personne ne pourrait partager. On n'expose que le nom et le courriel, soit
         *     ce qu'un carnet d'adresses montrerait — ni les groupes, ni le role, ni la
         *     date de derniere venue.
         *
         *     On ne connait que les personnes deja passees : aucune API OIDC standard ne
         *     permet de lister les comptes d'un fournisseur.
         */
        get: operations["list_people_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artists */
        get: operations["list_artists_api_artists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artists/{artist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artist */
        get: operations["get_artist_api_artists__artist_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Albums */
        get: operations["list_albums_api_albums_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/albums/{album_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Album */
        get: operations["get_album_api_albums__album_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Album */
        patch: operations["update_album_api_albums__album_id__patch"];
        trace?: never;
    };
    "/api/tracks/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Track */
        get: operations["get_track_api_tracks__track_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Track */
        patch: operations["update_track_api_tracks__track_id__patch"];
        trace?: never;
    };
    "/api/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Genres
         * @description Genres presents au catalogue, avec leur volume.
         */
        get: operations["list_genres_api_genres_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{track_id}/lyrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lyrics
         * @description Paroles d'une piste, servies a part car la colonne est differee.
         */
        get: operations["get_lyrics_api_tracks__track_id__lyrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Playlists
         * @description Les miennes et celles qu'on m'a partagees, les plus recentes d'abord.
         */
        get: operations["list_playlists_api_playlists_get"];
        put?: never;
        /** Create Playlist */
        post: operations["create_playlist_api_playlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{playlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Playlist */
        get: operations["get_playlist_api_playlists__playlist_id__get"];
        put?: never;
        post?: never;
        /** Delete Playlist */
        delete: operations["delete_playlist_api_playlists__playlist_id__delete"];
        options?: never;
        head?: never;
        /** Rename Playlist */
        patch: operations["rename_playlist_api_playlists__playlist_id__patch"];
        trace?: never;
    };
    "/api/playlists/{playlist_id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Tracks
         * @description Ajoute des titres, ou tout un album, a la suite.
         *
         *     Les doublons sont acceptes : mettre deux fois le meme titre est parfois
         *     voulu, et l'interdire surprendrait plus que ca n'aiderait.
         */
        post: operations["add_tracks_api_playlists__playlist_id__tracks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{playlist_id}/tracks/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Track */
        delete: operations["remove_track_api_playlists__playlist_id__tracks__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{playlist_id}/shares/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Share
         * @description Partage la playlist, ou change le droit accorde.
         */
        put: operations["set_share_api_playlists__playlist_id__shares__user_id__put"];
        post?: never;
        /** Remove Share */
        delete: operations["remove_share_api_playlists__playlist_id__shares__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{track_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Track
         * @description Redirige vers une URL presignee au lieu de relayer le flux.
         *
         *     Le navigateur telecharge alors directement depuis MinIO : il gere lui-meme
         *     les requetes Range (donc le deplacement dans le morceau) et l'API ne
         *     consomme ni bande passante ni worker pendant la lecture.
         */
        get: operations["stream_track_api_tracks__track_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/albums/{album_id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Album Cover */
        get: operations["album_cover_api_albums__album_id__cover_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add To Queue */
        post: operations["add_to_queue_api_sessions__session_id__queue_post"];
        /** Clear Queue */
        delete: operations["clear_queue_api_sessions__session_id__queue_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/queue/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove From Queue */
        delete: operations["remove_from_queue_api_sessions__session_id__queue__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/queue/{item_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move In Queue */
        post: operations["move_in_queue_api_sessions__session_id__queue__item_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Play */
        post: operations["play_api_sessions__session_id__play_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause */
        post: operations["pause_api_sessions__session_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Next Track */
        post: operations["next_track_api_sessions__session_id__next_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/previous": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Previous Track */
        post: operations["previous_track_api_sessions__session_id__previous_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/seek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seek */
        post: operations["seek_api_sessions__session_id__seek_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapcast/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_snapcast_config_get"];
        /** Update Config */
        put: operations["update_config_api_snapcast_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapcast/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Etat du serveur. Ne leve jamais : l'interface doit pouvoir afficher
         *     proprement un snapserver injoignable plutot que de casser la page.
         */
        get: operations["get_status_api_snapcast_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapcast/clients/{client_id}/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Client Volume */
        post: operations["set_client_volume_api_snapcast_clients__client_id__volume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapcast/clients/{client_id}/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Client Name */
        put: operations["set_client_name_api_snapcast_clients__client_id__name_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapcast/groups/{group_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Group Stream */
        post: operations["set_group_stream_api_snapcast_groups__group_id__stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapcast/groups/{group_id}/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Group Clients
         * @description Compose un groupe : deplace des appareils vers lui, quel que soit le
         *     groupe (ephemere) auquel ils appartenaient jusque-la.
         */
        post: operations["set_group_clients_api_snapcast_groups__group_id__clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapcast/groups/{group_id}/mute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Group Mute */
        post: operations["set_group_mute_api_snapcast_groups__group_id__mute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapcast/groups/{group_id}/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Group Name */
        put: operations["set_group_name_api_snapcast_groups__group_id__name_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Scan */
        post: operations["start_scan_api_admin_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/scan/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan Status
         * @description Dernier scan lance, en cours ou termine.
         */
        get: operations["scan_status_api_admin_scan_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/scan/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan History */
        get: operations["scan_history_api_admin_scan_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/scan/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan Errors
         * @description Erreurs du scan demande, ou du dernier scan par defaut.
         */
        get: operations["scan_errors_api_admin_scan_errors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Les personnes deja connectees, les plus recentes d'abord.
         *
         *     Il n'y a personne d'autre a proposer : aucune API OIDC standard ne permet
         *     de lister les comptes d'un fournisseur. On ne promeut donc que quelqu'un
         *     qui s'est deja connecte au moins une fois.
         */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Admin
         * @description Accorde ou retire le role d'administrateur.
         */
        put: operations["set_admin_api_admin_users__user_id__admin_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminUpdate */
        AdminUpdate: {
            /** Is Admin */
            is_admin: boolean;
        };
        /** AlbumDetail */
        AlbumDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Year */
            year: number | null;
            /** Artist Id */
            artist_id: number;
            /** Artist Name */
            artist_name: string;
            /** Has Cover */
            has_cover: boolean;
            /**
             * Track Count
             * @default 0
             */
            track_count: number;
            /** Genre */
            genre?: string | null;
            /**
             * Overrides
             * @default {}
             */
            overrides: {
                [key: string]: unknown;
            };
            /** Tracks */
            tracks: components["schemas"]["TrackOut"][];
        };
        /** AlbumOut */
        AlbumOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Year */
            year: number | null;
            /** Artist Id */
            artist_id: number;
            /** Artist Name */
            artist_name: string;
            /** Has Cover */
            has_cover: boolean;
            /**
             * Track Count
             * @default 0
             */
            track_count: number;
            /** Genre */
            genre?: string | null;
            /**
             * Overrides
             * @default {}
             */
            overrides: {
                [key: string]: unknown;
            };
        };
        /** AlbumUpdate */
        AlbumUpdate: {
            /** Title */
            title?: string | null;
            /** Year */
            year?: number | null;
        };
        /** ArtistDetail */
        ArtistDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Album Count
             * @default 0
             */
            album_count: number;
            /** Albums */
            albums: components["schemas"]["AlbumOut"][];
            /** Appears On */
            appears_on: components["schemas"]["TrackOut"][];
        };
        /** ArtistOut */
        ArtistOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Album Count
             * @default 0
             */
            album_count: number;
        };
        /**
         * AuthStatus
         * @description Ce que l'interface doit savoir pour afficher, ou non, une connexion.
         */
        AuthStatus: {
            /** Oidc Enabled */
            oidc_enabled: boolean;
            /** Authenticated */
            authenticated: boolean;
            /** Subject */
            subject: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Groups */
            groups: string[];
            /** Role */
            role: string;
            /** Is Super Admin */
            is_super_admin: boolean;
        };
        /** ClientsUpdate */
        ClientsUpdate: {
            /** Client Ids */
            client_ids: string[];
        };
        /** GenreOut */
        GenreOut: {
            /** Name */
            name: string;
            /** Album Count */
            album_count: number;
            /** Track Count */
            track_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LyricsOut */
        LyricsOut: {
            /** Track Id */
            track_id: number;
            /** Lyrics */
            lyrics: string | null;
        };
        /** MoveItem */
        MoveItem: {
            /** To Index */
            to_index: number;
        };
        /** MuteUpdate */
        MuteUpdate: {
            /** Muted */
            muted: boolean;
        };
        /** NameUpdate */
        NameUpdate: {
            /** Name */
            name: string;
        };
        /** Page[AlbumOut] */
        Page_AlbumOut_: {
            /** Items */
            items: components["schemas"]["AlbumOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[ArtistOut] */
        Page_ArtistOut_: {
            /** Items */
            items: components["schemas"]["ArtistOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * PersonOut
         * @description Une personne connue, telle qu'un selecteur de partage l'affiche.
         */
        PersonOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Email */
            email: string;
        };
        /** PlaylistCreate */
        PlaylistCreate: {
            /** Name */
            name: string;
        };
        /** PlaylistDetail */
        PlaylistDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Owner Name */
            owner_name: string;
            /** Is Owner */
            is_owner: boolean;
            /** Can Edit */
            can_edit: boolean;
            /** Track Count */
            track_count: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Items */
            items: components["schemas"]["PlaylistItemOut"][];
            /** Shares */
            shares: components["schemas"]["PlaylistShareOut"][];
        };
        /** PlaylistItemOut */
        PlaylistItemOut: {
            /** Id */
            id: number;
            track: components["schemas"]["TrackOut"];
            /** Added By */
            added_by: string | null;
        };
        /** PlaylistOut */
        PlaylistOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Owner Name */
            owner_name: string;
            /** Is Owner */
            is_owner: boolean;
            /** Can Edit */
            can_edit: boolean;
            /** Track Count */
            track_count: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PlaylistShareOut */
        PlaylistShareOut: {
            /** User Id */
            user_id: number;
            /** Name */
            name: string;
            /** Can Edit */
            can_edit: boolean;
        };
        /**
         * PlaylistTracksAdd
         * @description Des titres nommes un par un, ou tout un album.
         */
        PlaylistTracksAdd: {
            /** Track Ids */
            track_ids?: number[] | null;
            /** Album Id */
            album_id?: number | null;
        };
        /**
         * QueueAdd
         * @description Ajout de pistes explicites et/ou de tous les titres d'un album.
         */
        QueueAdd: {
            /**
             * Track Ids
             * @default []
             */
            track_ids: number[];
            /** Album Id */
            album_id?: number | null;
        };
        /** QueueItemOut */
        QueueItemOut: {
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Added By */
            added_by: string;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            track: components["schemas"]["TrackOut"];
        };
        /** ScanErrorOut */
        ScanErrorOut: {
            /** Id */
            id: number;
            /** Object Key */
            object_key: string;
            /** Message */
            message: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ScanRunOut */
        ScanRunOut: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Files Seen */
            files_seen: number;
            /** Files Indexed */
            files_indexed: number;
            /** Files Removed */
            files_removed: number;
            /** Files Failed */
            files_failed: number;
            /** Error */
            error: string | null;
        };
        /** SearchResults */
        SearchResults: {
            /** Artists */
            artists: components["schemas"]["ArtistOut"][];
            /** Albums */
            albums: components["schemas"]["AlbumOut"][];
            /** Tracks */
            tracks: components["schemas"]["TrackOut"][];
        };
        /** SeekRequest */
        SeekRequest: {
            /** Position S */
            position_s: number;
        };
        /** SessionCreate */
        SessionCreate: {
            /** Name */
            name: string;
        };
        /** SessionDetail */
        SessionDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Created By */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Snapcast Stream Id */
            snapcast_stream_id: string | null;
            /**
             * Item Count
             * @default 0
             */
            item_count: number;
            /** Items */
            items: components["schemas"]["QueueItemOut"][];
            /** Current Item Id */
            current_item_id: number | null;
            /** Is Playing */
            is_playing: boolean;
            /** Position S */
            position_s: number;
            /** Command Seq */
            command_seq: number;
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Created By */
            created_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Snapcast Stream Id */
            snapcast_stream_id: string | null;
            /**
             * Item Count
             * @default 0
             */
            item_count: number;
        };
        /** ShareUpdate */
        ShareUpdate: {
            /**
             * Can Edit
             * @default false
             */
            can_edit: boolean;
        };
        /** SnapcastConfig */
        SnapcastConfig: {
            /** Host */
            host: string;
            /**
             * Http Port
             * @default 1780
             */
            http_port: number;
            /** Enabled */
            enabled: boolean;
            /** Advertise Host */
            advertise_host: string;
        };
        /** StreamUpdate */
        StreamUpdate: {
            /** Stream Id */
            stream_id: string;
        };
        /** TrackOut */
        TrackOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Track No */
            track_no: number | null;
            /** Disc No */
            disc_no: number | null;
            /** Duration S */
            duration_s: number | null;
            /** Format */
            format: string | null;
            /** Bitrate */
            bitrate: number | null;
            /** Album Id */
            album_id: number;
            /** Album Title */
            album_title: string;
            /** Artist Id */
            artist_id: number;
            /** Artist Name */
            artist_name: string;
            /** Has Cover */
            has_cover: boolean;
            /** Genre */
            genre?: string | null;
            /**
             * Has Lyrics
             * @default false
             */
            has_lyrics: boolean;
            /**
             * Overrides
             * @default {}
             */
            overrides: {
                [key: string]: unknown;
            };
        };
        /**
         * TrackUpdate
         * @description Champs editables d'une piste. Absent = inchange, null = correction retiree.
         */
        TrackUpdate: {
            /** Title */
            title?: string | null;
            /** Track No */
            track_no?: number | null;
            /** Disc No */
            disc_no?: number | null;
        };
        /**
         * UserOut
         * @description Une personne deja connectee, telle que la page Administration l'affiche.
         */
        UserOut: {
            /** Id */
            id: number;
            /** Subject */
            subject: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Is Admin */
            is_admin: boolean;
            /** Is Super Admin */
            is_super_admin: boolean;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolumeUpdate */
        VolumeUpdate: {
            /** Percent */
            percent: number;
            /**
             * Muted
             * @default false
             */
            muted: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    callback_api_auth_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
                error_description?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | null;
                    };
                };
            };
        };
    };
    list_people_api_users_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artists_api_artists_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ArtistOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artist_api_artists__artist_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                artist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_albums_api_albums_get: {
        parameters: {
            query?: {
                q?: string | null;
                artist_id?: number | null;
                genre?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AlbumOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_album_api_albums__album_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                album_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_album_api_albums__album_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                album_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlbumUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_track_api_tracks__track_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_track_api_tracks__track_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_genres_api_genres_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenreOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lyrics_api_tracks__track_id__lyrics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LyricsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_playlists_api_playlists_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_playlist_api_playlists_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaylistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_playlist_api_playlists__playlist_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_playlist_api_playlists__playlist_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_playlist_api_playlists__playlist_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaylistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_tracks_api_playlists__playlist_id__tracks_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaylistTracksAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_track_api_playlists__playlist_id__tracks__item_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                playlist_id: number;
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_share_api_playlists__playlist_id__shares__user_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                playlist_id: number;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_share_api_playlists__playlist_id__shares__user_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                playlist_id: number;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_track_api_tracks__track_id__stream_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    album_cover_api_albums__album_id__cover_get: {
        parameters: {
            query?: {
                size?: string;
            };
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                album_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_queue_api_sessions__session_id__queue_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_queue_api_sessions__session_id__queue_delete: {
        parameters: {
            query?: {
                keep_current?: boolean;
            };
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_queue_api_sessions__session_id__queue__item_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                session_id: number;
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_in_queue_api_sessions__session_id__queue__item_id__move_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                session_id: number;
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveItem"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    play_api_sessions__session_id__play_post: {
        parameters: {
            query?: {
                item_id?: number | null;
            };
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_api_sessions__session_id__pause_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    next_track_api_sessions__session_id__next_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    previous_track_api_sessions__session_id__previous_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seek_api_sessions__session_id__seek_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeekRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_snapcast_config_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_config_api_snapcast_config_put: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapcastConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_snapcast_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_client_volume_api_snapcast_clients__client_id__volume_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VolumeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_client_name_api_snapcast_clients__client_id__name_put: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NameUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_group_stream_api_snapcast_groups__group_id__stream_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_group_clients_api_snapcast_groups__group_id__clients_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_group_mute_api_snapcast_groups__group_id__mute_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MuteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_group_name_api_snapcast_groups__group_id__name_put: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NameUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_scan_api_admin_scan_post: {
        parameters: {
            query?: {
                /** @description Relit tous les fichiers au lieu des seuls modifies. A utiliser apres une evolution de la lecture des tags : un scan normal ne retelecharge jamais un fichier dont l'etag n'a pas change. */
                force?: boolean;
            };
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_status_api_admin_scan_status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanRunOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_history_api_admin_scan_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_errors_api_admin_scan_errors_get: {
        parameters: {
            query?: {
                run_id?: number | null;
                limit?: number;
            };
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanErrorOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_admin_api_admin_users__user_id__admin_put: {
        parameters: {
            query?: never;
            header?: {
                "x-user-name"?: string | null;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
